"""
esttab_csv_to_markdown.py
--------------------------
Convert esttab-generated CSV files to readable GitHub-flavored markdown tables.

Usage:
    python esttab_csv_to_markdown.py <input_dir> <output_dir> [<summary_filename>]

Reads all *.csv files in <input_dir> (typically esttab's csv-format output),
writes a parallel *.md file for each in <output_dir>.

If <summary_filename> is provided, ALSO writes a combined master markdown to
<output_dir>/<summary_filename> containing all the individual tables with
section headers.  Useful for table-batches that want a single coauthor-
shareable artifact (e.g. a robustness battery).  Omit this arg to preserve
the existing 2-arg behavior (per-CSV MDs only, no master file).

Why this exists:
    esttab's native markdown support is limited, and this project does not
    have an esttab_md.ado helper.  Rather than build a custom Stata ado-file,
    we use esttab's well-tested csv format as an intermediate and post-process
    in Python.  This decouples the table data (Stata) from the markdown
    rendering (Python), which lets either side evolve independently.

esttab CSV layout we expect (cells may be wrapped in ="..." for Excel):
    ,(1),(2),(3)
    X1,-84.10***,21.50,32.40*
    ,(15.2),(12.1),(13.4)
    cov1,,12.3*,11.4
    ,,(4.5),(3.9)
    N,25,25,25
    R-squared,0.012,0.435,0.589

Output markdown table:
    |          | (1)      | (2)   | (3)    |
    |----------|----------|-------|--------|
    | X1       | -84.10***| 21.50 | 32.40* |
    |          | (15.2)   | (12.1)| (13.4) |
    | cov1     |          | 12.3* | 11.4   |
    |          |          | (4.5) | (3.9)  |
    | N        | 25       | 25    | 25     |
    | R-squared| 0.012    | 0.435 | 0.589  |

This script intentionally does NOT try to be clever about combining coef + SE
into one cell (e.g., "X1: -84.10*** (15.2)").  Keeping rows separate matches
the LaTeX cascade-table layout, so the markdown twin is a faithful 1:1 of the
LaTeX paper output.

Author:   Nicholas A Jensen
Date:     2026-05-20
"""

import csv
import sys
from pathlib import Path


def clean_cell(cell: str) -> str:
    """Strip whitespace and esttab's Excel-compatibility wrapping (="...")."""
    c = cell.strip()
    if c.startswith('="') and c.endswith('"'):
        c = c[2:-1]
    return c


def csv_to_md(csv_path: Path, md_path: Path) -> None:
    """Convert one esttab CSV file to a markdown table."""
    with csv_path.open("r", encoding="utf-8", newline="") as f:
        reader = csv.reader(f)
        # Keep blank rows out -- esttab sometimes pads with empty lines
        rows = [r for r in reader if any(cell.strip() for cell in r)]

    if not rows:
        md_path.write_text(
            f"_(empty CSV: {csv_path.name})_\n", encoding="utf-8"
        )
        return

    cleaned = [[clean_cell(c) for c in row] for row in rows]
    n_cols = max(len(r) for r in cleaned)
    padded = [r + [""] * (n_cols - len(r)) for r in cleaned]

    # Column widths for pretty alignment (optional but nice for human reading)
    widths = [
        max(len(r[i]) for r in padded) for i in range(n_cols)
    ]

    def fmt_row(row):
        return "| " + " | ".join(
            cell.ljust(widths[i]) for i, cell in enumerate(row)
        ) + " |"

    lines = []
    # Header is the first row
    lines.append(fmt_row(padded[0]))
    # Separator
    lines.append(
        "|" + "|".join("-" * (widths[i] + 2) for i in range(n_cols)) + "|"
    )
    # Body
    for row in padded[1:]:
        lines.append(fmt_row(row))

    md_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_summary(md_paths: list[Path], summary_path: Path) -> None:
    """Concatenate per-CSV markdowns into a single master with section
    headers.  Section titles are derived from the .md filename stem.
    """
    parts = [
        "# Combined table summary",
        "",
        (
            f"Auto-generated by `esttab_csv_to_markdown.py` from "
            f"{len(md_paths)} esttab CSV intermediates.  Tables listed in "
            f"alphabetical order of source filename."
        ),
        "",
        "---",
        "",
    ]
    for i, md_path in enumerate(md_paths, start=1):
        # Section title from stem; strip common prefixes for readability
        title = md_path.stem.replace("_", " ").strip()
        parts.append(f"## Table {i} — {title}")
        parts.append("")
        try:
            content = md_path.read_text(encoding="utf-8").rstrip()
        except Exception as e:
            content = f"_(error reading {md_path.name}: {e})_"
        parts.append(content)
        parts.append("")
        parts.append("---")
        parts.append("")
    summary_path.write_text("\n".join(parts), encoding="utf-8")


def main() -> int:
    if len(sys.argv) not in (3, 4):
        print(
            "Usage: python esttab_csv_to_markdown.py "
            "<input_dir> <output_dir> [<summary_filename>]",
            file=sys.stderr,
        )
        return 2

    input_dir = Path(sys.argv[1])
    output_dir = Path(sys.argv[2])
    summary_filename = sys.argv[3] if len(sys.argv) == 4 else None

    if not input_dir.is_dir():
        print(f"Error: input dir not found: {input_dir}", file=sys.stderr)
        return 1
    output_dir.mkdir(parents=True, exist_ok=True)

    csvs = sorted(input_dir.glob("*.csv"))
    if not csvs:
        print(f"No *.csv files found in {input_dir}", file=sys.stderr)
        return 1

    n_ok = 0
    n_err = 0
    md_paths = []
    for csv_path in csvs:
        md_path = output_dir / (csv_path.stem + ".md")
        try:
            csv_to_md(csv_path, md_path)
            print(f"  {csv_path.name} -> {md_path.name}")
            md_paths.append(md_path)
            n_ok += 1
        except Exception as e:
            print(
                f"  ERROR converting {csv_path.name}: {e}", file=sys.stderr
            )
            n_err += 1

    print(
        f"\nConverted {n_ok} / {len(csvs)} CSV files to markdown "
        f"({n_err} errors)."
    )

    # Optional combined master
    if summary_filename and md_paths:
        summary_path = output_dir / summary_filename
        try:
            write_summary(md_paths, summary_path)
            print(
                f"Wrote combined summary: {summary_path.name} "
                f"({len(md_paths)} tables)"
            )
        except Exception as e:
            print(f"  ERROR writing summary: {e}", file=sys.stderr)
            n_err += 1

    return 0 if n_err == 0 else 1


if __name__ == "__main__":
    sys.exit(main())
